export const restaurantList = [
  {
    id: 1,
    movie: "The Shawshank Redemption",
    rating: 9.2,
    image: "images/shawshank.jpg",
    imdb_url: "https://www.imdb.com/title/tt0111161/",
  },
  {
    id: 2,
    movie: "The Godfather",
    rating: 9.2,
    image: "images/godfather.jpg",
    imdb_url: "https://www.imdb.com/title/tt0068646/",
  },
  {
    id: 3,
    movie: "The Dark Knight",
    rating: 9,
    image: "images/dark_knight.jpg",
    imdb_url: "https://www.imdb.com/title/tt0468569/",
  },
  {
    id: 4,
    movie: "Pulp Fiction",
    rating: 8.9,
    image: "images/pulp_fiction.jpg",
    imdb_url: "https://www.imdb.com/title/tt0110912/",
  },
  {
    id: 5,
    movie: "The Lord of the Rings: The Return of the King",
    rating: 9,
    image: "images/lotr_return_king.jpg",
    imdb_url: "https://www.imdb.com/title/tt0167260/",
  },
  {
    id: 6,
    movie: "The Good, the Bad and the Ugly",
    rating: 8.8,
    image: "images/good_bad_ugly.jpg",
    imdb_url: "https://www.imdb.com/title/tt0060196/",
  },
  {
    id: 7,
    movie: "Fight Club",
    rating: 8.8,
    image: "images/fight_club.jpg",
    imdb_url: "https://www.imdb.com/title/tt0137523/",
  },
  {
    id: 8,
    movie: "The Lord of the Rings: The Fellowship of the Ring",
    rating: 8.8,
    image: "images/lotr_fellowship.jpg",
    imdb_url: "https://www.imdb.com/title/tt0120737/",
  },
  {
    id: 9,
    movie: "Forrest Gump",
    rating: 8.8,
    image: "images/forrest_gump.jpg",
    imdb_url: "https://www.imdb.com/title/tt0109830/",
  },
  {
    id: 10,
    movie: "Inception",
    rating: 8.8,
    image: "images/inception.jpg",
    imdb_url: "https://www.imdb.com/title/tt1375666/",
  },
  {
    id: 11,
    movie: "Interstellar",
    rating: 8.6,
    image: "images/interstellar.jpg",
    imdb_url: "https://www.imdb.com/title/tt0816692/",
  },
  {
    id: 12,
    movie: "The Matrix",
    rating: 8.7,
    image: "images/matrix.jpg",
    imdb_url: "https://www.imdb.com/title/tt0133093/",
  },
  {
    id: 13,
    movie: "Schindler's List",
    rating: 8.9,
    image: "images/schindlers_list.jpg",
    imdb_url: "https://www.imdb.com/title/tt0108052/",
  },
  {
    id: 14,
    movie: "The Silence of the Lambs",
    rating: 8.6,
    image: "images/silence_lambs.jpg",
    imdb_url: "https://www.imdb.com/title/tt0102926/",
  },
  {
    id: 15,
    movie: "Star Wars: Episode V - The Empire Strikes Back",
    rating: 8.7,
    image: "images/empire_strikes_back.jpg",
    imdb_url: "https://www.imdb.com/title/tt0080684/",
  },
];
